# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_previewui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class PlotPreviewForm(object):
    def setupUi(self, parent):
        parent.setObjectName("parent")
        parent.resize(545, 307)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.sizePolicy().hasHeightForWidth())
        parent.setSizePolicy(sizePolicy)
        parent.centralwidget = QtWidgets.QWidget(parent)
        parent.centralwidget.setObjectName("centralwidget")
        parent.gridLayout_2 = QtWidgets.QGridLayout(parent.centralwidget)
        parent.gridLayout_2.setObjectName("gridLayout_2")
        parent.frame = QtWidgets.QFrame(parent.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parent.frame.sizePolicy().hasHeightForWidth())
        parent.frame.setSizePolicy(sizePolicy)
        parent.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        parent.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        parent.frame.setObjectName("frame")
        parent.gridLayout_4 = QtWidgets.QGridLayout(parent.frame)
        parent.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        parent.gridLayout_4.setHorizontalSpacing(4)
        parent.gridLayout_4.setObjectName("gridLayout_4")
        parent.PlotGridLayout = QtWidgets.QGridLayout()
        parent.PlotGridLayout.setSpacing(0)
        parent.PlotGridLayout.setObjectName("PlotGridLayout")
        parent.gridLayout_4.addLayout(parent.PlotGridLayout, 0, 0, 1, 1)
        parent.gridLayout_2.addWidget(parent.frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        parent.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        parent.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        parent.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        parent.horizontalLayout_2.addItem(spacerItem1)
        parent.horizontalLayout = QtWidgets.QHBoxLayout()
        parent.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        parent.horizontalLayout.setObjectName("horizontalLayout")
        parent.cancelPushButton = QtWidgets.QPushButton(parent.centralwidget)
        parent.cancelPushButton.setObjectName("cancelPushButton")
        parent.horizontalLayout.addWidget(parent.cancelPushButton)
        parent.savePushButton = QtWidgets.QPushButton(parent.centralwidget)
        parent.savePushButton.setObjectName("savePushButton")
        parent.saveAsPushButton = QtWidgets.QPushButton(parent.centralwidget)
        parent.saveAsPushButton.setObjectName("saveAsPushButton")
        parent.horizontalLayout.addWidget(parent.saveAsPushButton)
        parent.horizontalLayout.addWidget(parent.savePushButton)
        parent.horizontalLayout_2.addLayout(parent.horizontalLayout)
        parent.gridLayout_2.addLayout(parent.horizontalLayout_2, 2, 0, 1, 1)
        parent.setCentralWidget(parent.centralwidget)

        self.retranslateUi(parent)
        QtCore.QMetaObject.connectSlotsByName(parent)

    def retranslateUi(self, parent):
        _translate = QtCore.QCoreApplication.translate
        parent.setWindowTitle(_translate("parent", "Plot Preview"))
        parent.cancelPushButton.setText(_translate("parent", "Cancel"))
        parent.savePushButton.setText(_translate("parent", "Save"))
        parent.saveAsPushButton.setText(_translate("parent", "Save As ..."))
